import { createBrowserClient } from '@supabase/ssr';

// Get the environment variables, ensuring they exist
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// Ensure environment variables are set
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Supabase environment variables are missing. Check your .env.local file.');
}

// Extract project ID from Supabase URL for cookie name
const projectId = supabaseUrl ? supabaseUrl.split('.')[0].split('//')[1] : '';
const cookieName = `sb-${projectId}-auth-token`;

console.log('[Supabase Client] Initializing client with URL:', supabaseUrl);
console.log('[Supabase Client] Using cookie:', cookieName);

// Function to log current cookies
const logCookies = () => {
  if (typeof window !== 'undefined') {
    console.log('[Supabase Client] Current cookies:', document.cookie);
  }
};

// Log initial cookies
if (typeof window !== 'undefined') {
  logCookies();
}

// Initialize the Supabase client with environment variables
export const supabase = createBrowserClient(
  supabaseUrl || '',
  supabaseAnonKey || '',
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      debug: true, // Enable detailed auth logs
      // Specific cookie settings
      cookieOptions: {
        // Use the default name generated by Supabase based on project ID
        name: cookieName,
        // Localhost needs to use SameSite=Lax
        sameSite: 'lax',
        // In development, secure should be false for localhost
        secure: process.env.NODE_ENV === 'production',
        // Path where the cookie is valid
        path: '/',
        // Increase cookie lifetime
        maxAge: 60 * 60 * 24 * 7, // 7 days
      }
    }
  }
);

// Log when client is initialized
console.log('[Supabase Client] Client initialized');

// Define interfaces for Supabase response
interface SupabaseUser {
  id: string;
  email?: string;
  [key: string]: any;
}

interface SupabaseSession {
  user: SupabaseUser;
  [key: string]: any;
}

interface SessionResponse {
  data: {
    session: SupabaseSession | null;
  }
}

// Type for authentication events
type AuthChangeEvent = 
  | 'INITIAL_SESSION'
  | 'SIGNED_IN'
  | 'SIGNED_OUT'
  | 'TOKEN_REFRESHED'
  | 'USER_UPDATED'
  | 'PASSWORD_RECOVERY';

// Check initial authentication state
supabase.auth.getSession().then((response: SessionResponse) => {
  console.log('[Supabase Client] Initial session:', response.data.session ? 'Active' : 'Inactive');
  if (response.data.session) {
    console.log('[Supabase Client] User logged in:', response.data.session.user.email);
  }
  
  // Log cookies after checking session
  logCookies();
});

// Add observer for session changes
supabase.auth.onAuthStateChange((event: AuthChangeEvent, session: SupabaseSession | null) => {
  console.log(`[Supabase Client] Authentication event: ${event}`);
  logCookies();
});

// Export a function to get an authenticated client
export const getSupabaseClient = () => {
  return supabase;
}; 